#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import sys
import types
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.parse import urlparse
from urllib.request import urlopen


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA_URL = (
    "https://github.com/prevedel-lab/brimfile/blob/main/"
    "src/brimfile/metadata/schema.py"
)
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "brim_file_metadata.md"

_ASCII_TRANSLATION = str.maketrans(
    {
        "‘": "'",
        "’": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
    }
)


def _normalize_text(value: str) -> str:
    return value.translate(_ASCII_TRANSLATION)


def _schema_url_to_raw(schema_url: str) -> str:
    parsed = urlparse(schema_url)
    if parsed.netloc not in {"github.com", "www.github.com"}:
        return schema_url

    path_parts = parsed.path.strip("/").split("/")
    if len(path_parts) < 5 or path_parts[2] != "blob":
        return schema_url

    owner, repo, _, branch = path_parts[:4]
    file_path = "/".join(path_parts[4:])
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{file_path}"


def _load_schema_module(schema_url: str) -> Any:
    raw_url = _schema_url_to_raw(schema_url)
    try:
        with urlopen(raw_url, timeout=30) as response:
            encoding = response.headers.get_content_charset() or "utf-8"
            source = response.read().decode(encoding)
    except URLError as exc:
        raise RuntimeError(
            f"Could not download schema module from {schema_url}: {exc}"
        ) from exc

    module = types.ModuleType("brimfile_metadata_schema")
    module.__file__ = raw_url
    sys.modules[module.__name__] = module
    exec(compile(source, raw_url, "exec"), module.__dict__)
    return module


def _python_type_to_label(python_type: Any) -> str:
    if python_type is str:
        return "string"
    if python_type is float:
        return "float"
    if python_type is int:
        return "int"
    if python_type is bool:
        return "bool"

    origin = getattr(python_type, "__origin__", None)
    if origin is list:
        args = getattr(python_type, "__args__", ())
        if args:
            return f"1D {_python_type_to_label(args[0])} array"
        return "1D array"

    name = getattr(python_type, "__name__", None)
    if name is not None:
        return name

    return str(python_type).replace("typing.", "")


def _field_type_label(field: Any) -> str:
    if field.enum_type is None:
        return _python_type_to_label(field.python_type)

    values = ", ".join(_normalize_text(str(item.value)) for item in field.enum_type)
    return f"enum {{{values}}}"


def _field_description_line(field: Any) -> str:
    type_label = _field_type_label(field)

    qualifiers: list[str] = []
    if not field.required:
        qualifiers.append("optional")
    if field.units_required:
        qualifiers.append("units required")
    qualifier_suffix = f" ({', '.join(qualifiers)})" if qualifiers else ""

    line = f"  - **'{field.name}' [{type_label}]**{qualifier_suffix}"
    description = _normalize_text(field.description.strip())
    if description:
        line += f": {description}"
    return _normalize_text(line)


def render_markdown(schema_module: Any, schema_source: str) -> str:
    lines: list[str] = [
        "# Proposal for metadata in version 0.1 of the brim file format",
        "",
        "<!-- This file is auto-generated by .github/scripts/generate_metadata_markdown.py. -->",
        f"<!-- Source metadata schema: {schema_source} -->",
        "",
        "The following metadata are defined with the aim of making Brillouin measurements interpretable and reproducible; they are based on the [Consensus Statement on Brillouin Light Scattering Microscopy of Biological Materials](https://doi.org/10.1038/s41566-025-01681-6).",
        "",
        "The units used the same conventions defined in the [main document](brim_file_specs.md).",
        "",
        "## Structure",
        "",
        "The `Metadata` attribute in `/Brillouin_data` has the following hierarchy (in JSON they are basically nested objects):",
    ]

    for section_type in schema_module.Type:
        lines.append(f"- /{section_type.value}")

    lines.extend([
        "",
        "## Detailed description of the metadata in the file",
    ])

    for section_type, fields in schema_module.METADATA_SCHEMA.items():
        lines.append(f"- **'/{section_type.value}'** has the following nested attributes:")
        for field in fields:
            lines.append(_field_description_line(field))

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate markdown documentation for metadata schema."
    )
    parser.add_argument(
        "--schema-url",
        default=DEFAULT_SCHEMA_URL,
        help=(
            "URL of metadata schema module "
            "(default: prevedel-lab/brimfile brim-validation branch)"
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to generated markdown file (default: docs/brim_file_metadata.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if output file does not match generated content.",
    )
    return parser.parse_args()


def _print_diff(expected: str, current: str, output_path: Path) -> None:
    expected_lines = expected.splitlines(keepends=True)
    current_lines = current.splitlines(keepends=True)
    diff = difflib.unified_diff(
        current_lines,
        expected_lines,
        fromfile=f"{output_path} (current)",
        tofile=f"{output_path} (expected)",
    )
    sys.stdout.writelines(diff)


def main() -> int:
    args = parse_args()
    schema_url: str = args.schema_url
    output_path: Path = args.output
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path

    schema_module = _load_schema_module(schema_url)
    generated = render_markdown(schema_module, schema_url)

    if args.check:
        if not output_path.exists():
            print(
                f"::error::{output_path} does not exist. "
                "Run .github/scripts/generate_metadata_markdown.py first."
            )
            return 1

        current = output_path.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"::error::{output_path} is not up to date with "
                f"{schema_url}"
            )
            _print_diff(generated, current, output_path)
            return 1

        print(f"{output_path} is up to date.")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated, encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
