name: Generate LinkML documentation

# build the documentation  with a manual trigger
on:
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ADJUST THIS: install all dependencies
      - run: pip install linkml
      - run: pip install mkdocs
      # ADJUST THIS: build your documentation into docs/.
      - run: gen-doc -d docs/ schema/brim_main.yaml
      # build the documentation into site/
      - run: mkdocs build
        working-directory: schema

      - uses: actions/upload-pages-artifact@v3
        with:
          path: schema/site/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
